### ISSUE TITLE
0.0.3 wheels not in flashinfer.ai/whl/ 

### ISSUE THREAD

**Issue by Qubitium** [flashinfer-ai/flashinfer#168]
Release 0.0.3 does not have proper wheels built/uploaded to https://flashinfer.ai/whl/cu121/torch2.2/flashinfer/

Please upload the prebuilt wheels. Thanks!

Normally this is not a problem but flashinfer is a quite a beast to compile.

**Comment by yzh119** [comment]
Hi @Qubitium , thanks for your notification.

> Please upload the prebuilt wheels. Thanks!

We have a continuous integration process that compiles and uploads wheels automatically, the latest run is still in progress: https://github.com/flashinfer-ai/flashinfer/actions/runs/8226582215, we are considering more CI machines to facilitate the process.

**Comment by Qubitium** [comment]
@yzh119  I am working on a PR to cut the compile time by quite a bit plus fix some other compile issues I have encountered. Will post it when ready.  Flashinfer will bring even my 48 core zen3 2x9334 to its knees. I am not cuda guru, but compile is something I can help with.

**Comment by yzh119** [comment]
That sounds great, thank you!

**Comment by Qubitium** [comment]
@yzh119  PR created. #171.

**Comment by yzh119** [comment]
Wheels are uploaded: https://github.com/flashinfer-ai/flashinfer/releases/tag/v0.0.3
