### ISSUE TITLE
QUESTION: C++ API support Ragged Tensor now?

### ISSUE THREAD

**Issue by yz-tang** [flashinfer-ai/flashinfer#189]
In the c++ unit test, I only found case about paged tensor。
How to use ragged tensor in c++？
When I try use **BatchPrefillWithRaggedKVCacheWrapper**, it will link error。

**Comment by yzh119** [comment]
Yes we support ragged tensors in C++ apis, we add some examples in #190.

Regarding your link issue, you can check whether you have instantiated the templates. We decouple the declaration and implementations to accelerate compilation speed, if you only include the declaration header, then you have to compile the template instantiations and link them properly (see our [CMakeLists](https://github.com/flashinfer-ai/flashinfer/blob/1df641f8781a3eb8e82e57488a93e4e45bb0ae75/CMakeLists.txt#L306)).
