### ISSUE TITLE
Support torch 2.3

### ISSUE THREAD

**Issue by rkooo567** [flashinfer-ai/flashinfer#227]
Hi! Thanks for the awesome library.

vLLM recently upgraded its torch version to 2.3.0. And we have issues when trying to integrate flash infer to it because it doesn't have a wheel built with torch 2.3 yet. Do you guys have any plan to have a release soon with wheels built with torch 2.3?

**Comment by yzh119** [comment]
Thank you for bringing this up, we are running the release scripts: https://github.com/flashinfer-ai/flashinfer/actions/runs/8920852220

**Comment by rkooo567** [comment]
Thanks for the update! I think we are very close to support flash infer for vllm, and we are very excited about it!

**Comment by yzh119** [comment]
Done in https://github.com/flashinfer-ai/flashinfer/releases/tag/v0.0.4
