### ISSUE TITLE
build raise  "cub::BlockAdjacentDifference<__nv_bool, 1024, 1, 1, 860>" has no member "SubtractLeft"

### ISSUE THREAD

**Issue by WanBenLe** [flashinfer-ai/flashinfer#261]
[1/1] /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output /root/autodl-tmp/wsl/flashinfer/python/build/temp.linux-x86_64-cpython-310/csrc/sampling.o.d -I/root/autodl-tmp/wsl/flashinfer/python/include -I/root/autodl-tmp/conda/envs/wslconda/lib/python3.10/site-packages/torch/include -I/root/autodl-tmp/conda/envs/wslconda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/root/autodl-tmp/conda/envs/wslconda/lib/python3.10/site-packages/torch/include/TH -I/root/autodl-tmp/conda/envs/wslconda/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda/include -I/root/autodl-tmp/conda/envs/wslconda/include/python3.10 -c -c /root/autodl-tmp/wsl/flashinfer/python/csrc/sampling.cu -o /root/autodl-tmp/wsl/flashinfer/python/build/temp.linux-x86_64-cpython-310/csrc/sampling.o --expt-relaxed-constexpr -DFLASHINFER_ENABLE_BF16 -DFLASHINFER_ENABLE_FP8 --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++17 --threads 8 -Xfatbin -compress-all -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_kernels -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86
        FAILED: /root/autodl-tmp/wsl/flashinfer/python/build/temp.linux-x86_64-cpython-310/csrc/sampling.o
        /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output /root/autodl-tmp/wsl/flashinfer/python/build/temp.linux-x86_64-cpython-310/csrc/sampling.o.d -I/root/autodl-tmp/wsl/flashinfer/python/include -I/root/autodl-tmp/conda/envs/wslconda/lib/python3.10/site-packages/torch/include -I/root/autodl-tmp/conda/envs/wslconda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/root/autodl-tmp/conda/envs/wslconda/lib/python3.10/site-packages/torch/include/TH -I/root/autodl-tmp/conda/envs/wslconda/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda/include -I/root/autodl-tmp/conda/envs/wslconda/include/python3.10 -c -c /root/autodl-tmp/wsl/flashinfer/python/csrc/sampling.cu -o /root/autodl-tmp/wsl/flashinfer/python/build/temp.linux-x86_64-cpython-310/csrc/sampling.o --expt-relaxed-constexpr -DFLASHINFER_ENABLE_BF16 -DFLASHINFER_ENABLE_FP8 --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++17 --threads 8 -Xfatbin -compress-all -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_kernels -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86
        /root/autodl-tmp/wsl/flashinfer/python/include/flashinfer/sampling.cuh(109): error: class "cub::BlockAdjacentDifference<__nv_bool, 1024, 1, 1, 860>" has no member "SubtractLeft"

**Comment by WanBenLe** [comment]
how can i fixed it?

**Comment by yzh119** [comment]
what's your cuda version?

**Comment by WanBenLe** [comment]
> what's your cuda version?

cuda11.8

**Comment by yzh119** [comment]
I think it's because cub do not support cuda arch 860, would you mind changing cuda architecture in compilation flags from 86 to 80?

```bash
TORCH_CUDA_ARCH_LIST="8.0" python setup.py install
```

**Comment by WanBenLe** [comment]
> I think it's because cub do not support cuda arch 860, would you mind changing cuda architecture in compilation flags from 86 to 80?
> 
> ```shell
> TORCH_CUDA_ARCH_LIST="8.0" python setup.py install
> ```
the error seem the same.


FAILED: /root/autodl-tmp/wsl/flashinfer/python/build/temp.linux-x86_64-cpython-310/csrc/sampling.o 
/usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output /root/autodl-tmp/wsl/flashinfer/python/build/temp.linux-x86_64-cpython-310/csrc/sampling.o.d -I/root/autodl-tmp/wsl/flashinfer/python/include -I/root/autodl-tmp/conda/envs/wslconda/lib/python3.10/site-packages/torch/include -I/root/autodl-tmp/conda/envs/wslconda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/root/autodl-tmp/conda/envs/wslconda/lib/python3.10/site-packages/torch/include/TH -I/root/autodl-tmp/conda/envs/wslconda/lib/python3.10/site-packages/torch/include/THC -I/usr/local/cuda/include -I/root/autodl-tmp/conda/envs/wslconda/include/python3.10 -c -c /root/autodl-tmp/wsl/flashinfer/python/csrc/sampling.cu -o /root/autodl-tmp/wsl/flashinfer/python/build/temp.linux-x86_64-cpython-310/csrc/sampling.o --expt-relaxed-constexpr -DFLASHINFER_ENABLE_BF16 -DFLASHINFER_ENABLE_FP8 --compiler-options ''"'"'-fPIC'"'"'' -O3 -std=c++17 --threads 8 -Xfatbin -compress-all -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_kernels -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_80,code=sm_80
/root/autodl-tmp/wsl/flashinfer/python/include/flashinfer/sampling.cuh(109): error: class "cub::BlockAdjacentDifference<__nv_bool, 1024, 1, 1, 800>" has no member "SubtractLeft"
          detected during:
            instantiation of "void flashinfer::sampling::DeviceSamplingFromProb(uint32_t, uint32_t, T, T, flashinfer::vec_t<T, VEC_SIZE>, T &, flashinfer::sampling::SamplingTempStorage<T, BLOCK_THREADS, SCAN_ALGORITHM, REDUCE_ALGORITHM> *) [with VEC_SIZE=16U, BLOCK_THREADS=1024U, SCAN_ALGORITHM=cub::BLOCK_SCAN_WARP_SCANS, REDUCE_ALGORITHM=cub::BLOCK_REDUCE_WARP_REDUCTIONS, T=float]" 
(148): here
            instantiation of "void flashinfer::sampling::SamplingFromProbKernel<BLOCK_THREADS,SCAN_ALGORITHM,REDUCE_ALGORITHM,VEC_SIZE,DType,IdType>(DType *, DType *, IdType *, IdType *, uint32_t) [with BLOCK_THREADS=1024U, SCAN_ALGORITHM=cub::BLOCK_SCAN_WARP_SCANS, REDUCE_ALGORITHM=cub::BLOCK_REDUCE_WARP_REDUCTIONS, VEC_SIZE=16U, DType=float, IdType=int]" 
(343): here
            instantiation of "cudaError_t flashinfer::sampling::SamplingFromProb(T *, T *, IdType *, uint32_t, uint32_t, cudaStream_t) [with T=float, IdType=int]" 
/root/autodl-tmp/wsl/flashinfer/python/csrc/sampling.cu(37): here

/root/autodl-tmp/wsl/flashinfer/python/include/flashinfer/sampling.cuh(109): warning #174-D: expression has no effect
          detected during:
            instantiation of "void flashinfer::sampling::DeviceSamplingFromProb(uint32_t, uint32_t, T, T, flashinfer::vec_t<T, VEC_SIZE>, T &, flashinfer::sampling::SamplingTempStorage<T, BLOCK_THREADS, SCAN_ALGORITHM, REDUCE_ALGORITHM> *) [with VEC_SIZE=16U, BLOCK_THREADS=1024U, SCAN_ALGORITHM=cub::BLOCK_SCAN_WARP_SCANS, REDUCE_ALGORITHM=cub::BLOCK_REDUCE_WARP_REDUCTIONS, T=float]" 
(148): here
            instantiation of "void flashinfer::sampling::SamplingFromProbKernel<BLOCK_THREADS,SCAN_ALGORITHM,REDUCE_ALGORITHM,VEC_SIZE,DType,IdType>(DType *, DType *, IdType *, IdType *, uint32_t) [with BLOCK_THREADS=1024U, SCAN_ALGORITHM=cub::BLOCK_SCAN_WARP_SCANS, REDUCE_ALGORITHM=cub::BLOCK_REDUCE_WARP_REDUCTIONS, VEC_SIZE=16U, DType=float, IdType=int]" 
(343): here
            instantiation of "cudaError_t flashinfer::sampling::SamplingFromProb(T *, T *, IdType *, uint32_t, uint32_t, cudaStream_t) [with T=float, IdType=int]" 
/root/autodl-tmp/wsl/flashinfer/python/csrc/sampling.cu(37): here

/root/autodl-tmp/wsl/flashinfer/python/include/flashinfer/sampling.cuh(109): warning #174-D: expression has no effect
          detected during:
            instantiation of "void flashinfer::sampling::DeviceSamplingFromProb(uint32_t, uint32_t, T, T, flashinfer::vec_t<T, VEC_SIZE>, T &, flashinfer::sampling::SamplingTempStorage<T, BLOCK_THREADS, SCAN_ALGORITHM, REDUCE_ALGORITHM> *) [with VEC_SIZE=16U, BLOCK_THREADS=1024U, SCAN_ALGORITHM=cub::BLOCK_SCAN_WARP_SCANS, REDUCE_ALGORITHM=cub::BLOCK_REDUCE_WARP_REDUCTIONS, T=float]" 
(148): here
            instantiation of "void flashinfer::sampling::SamplingFromProbKernel<BLOCK_THREADS,SCAN_ALGORITHM,REDUCE_ALGORITHM,VEC_SIZE,DType,IdType>(DType *, DType *, IdType *, IdType *, uint32_t) [with BLOCK_THREADS=1024U, SCAN_ALGORITHM=cub::BLOCK_SCAN_WARP_SCANS, REDUCE_ALGORITHM=cub::BLOCK_REDUCE_WARP_REDUCTIONS, VEC_SIZE=16U, DType=float, IdType=int]" 
(343): here
            instantiation of "cudaError_t flashinfer::sampling::SamplingFromProb(T *, T *, IdType *, uint32_t, uint32_t, cudaStream_t) [with T=float, IdType=int]" 
/root/autodl-tmp/wsl/flashinfer/python/csrc/sampling.cu(37): here

/root/autodl-tmp/wsl/flashinfer/python/include/flashinfer/sampling.cuh(109): error: class "cub::BlockAdjacentDifference<__nv_bool, 1024, 1, 1, 800>" has no member "SubtractLeft"
          detected during:
            instantiation of "void flashinfer::sampling::DeviceSamplingFromProb(uint32_t, uint32_t, T, T, flashinfer::vec_t<T, VEC_SIZE>, T &, flashinfer::sampling::SamplingTempStorage<T, BLOCK_THREADS, SCAN_ALGORITHM, REDUCE_ALGORITHM> *) [with VEC_SIZE=8U, BLOCK_THREADS=1024U, SCAN_ALGORITHM=cub::BLOCK_SCAN_WARP_SCANS, REDUCE_ALGORITHM=cub::BLOCK_REDUCE_WARP_REDUCTIONS, T=float]" 
(148): here
            instantiation of "void flashinfer::sampling::SamplingFromProbKernel<BLOCK_THREADS,SCAN_ALGORITHM,REDUCE_ALGORITHM,VEC_SIZE,DType,IdType>(DType *, DType *, IdType *, IdType *, uint32_t) [with BLOCK_THREADS=1024U, SCAN_ALGORITHM=cub::BLOCK_SCAN_WARP_SCANS, REDUCE_ALGORITHM=cub::BLOCK_REDUCE_WARP_REDUCTIONS, VEC_SIZE=8U, DType=float, IdType=int]" 
(343): here
            instantiation of "cudaError_t flashinfer::sampling::SamplingFromProb(T *, T *, IdType *, uint32_t, uint32_t, cudaStream_t) [with T=float, IdType=int]" 
/root/autodl-tmp/wsl/flashinfer/python/csrc/sampling.cu(37): here

/root/autodl-tmp/wsl/flashinfer/python/include/flashinfer/sampling.cuh(109): warning #174-D: expression has no effect
          detected during:
            instantiation of "void flashinfer::sampling::DeviceSamplingFromProb(uint32_t, uint32_t, T, T, flashinfer::vec_t<T, VEC_SIZE>, T &, flashinfer::sampling::SamplingTempStorage<T, BLOCK_THREADS, SCAN_ALGORITHM, REDUCE_ALGORITHM> *) [with VEC_SIZE=8U, BLOCK_THREADS=1024U, SCAN_ALGORITHM=cub::BLOCK_SCAN_WARP_SCANS, REDUCE_ALGORITHM=cub::BLOCK_REDUCE_WARP_REDUCTIONS, T=float]" 
(148): here
            instantiation of "void flashinfer::sampling::SamplingFromProbKernel<BLOCK_THREADS,SCAN_ALGORITHM,REDUCE_ALGORITHM,VEC_SIZE,DType,IdType>(DType *, DType *, IdType *, IdType *, uint32_t) [with BLOCK_THREADS=1024U, SCAN_ALGORITHM=cub::BLOCK_SCAN_WARP_SCANS, REDUCE_ALGORITHM=cub::BLOCK_REDUCE_WARP_REDUCTIONS, VEC_SIZE=8U, DType=float, IdType=int]" 
(343): here
            instantiation of "cudaError_t flashinfer::sampling::SamplingFromProb(T *, T *, IdType *, uint32_t, uint32_t, cudaStream_t) [with T=float, IdType=int]" 
/root/autodl-tmp/wsl/flashinfer/python/csrc/sampling.cu(37): here

/root/autodl-tmp/wsl/flashinfer/python/include/flashinfer/sampling.cuh(109): warning #174-D: expression has no effect
          detected during:
            instantiation of "void flashinfer::sampling::DeviceSamplingFromProb(uint32_t, uint32_t, T, T, flashinfer::vec_t<T, VEC_SIZE>, T &, flashinfer::sampling::SamplingTempStorage<T, BLOCK_THREADS, SCAN_ALGORITHM, REDUCE_ALGORITHM> *) [with VEC_SIZE=8U, BLOCK_THREADS=1024U, SCAN_ALGORITHM=cub::BLOCK_SCAN_WARP_SCANS, REDUCE_ALGORITHM=cub::BLOCK_REDUCE_WARP_REDUCTIONS, T=float]" 
(148): here
            instantiation of "void flashinfer::sampling::SamplingFromProbKernel<BLOCK_THREADS,SCAN_ALGORITHM,REDUCE_ALGORITHM,VEC_SIZE,DType,IdType>(DType *, DType *, IdType *, IdType *, uint32_t) [with BLOCK_THREADS=1024U, SCAN_ALGORITHM=cub::BLOCK_SCAN_WARP_SCANS, REDUCE_ALGORITHM=cub::BLOCK_REDUCE_WARP_REDUCTIONS, VEC_SIZE=8U, DType=float, IdType=int]" 
(343): here
            instantiation of "cudaError_t flashinfer::sampling::SamplingFromProb(T *, T *, IdType *, uint32_t, uint32_t, cudaStream_t) [with T=float, IdType=int]" 
/root/autodl-tmp/wsl/flashinfer/python/csrc/sampling.cu(37): here

/root/autodl-tmp/wsl/flashinfer/python/include/flashinfer/sampling.cuh(109): error: class "cub::BlockAdjacentDifference<__nv_bool, 1024, 1, 1, 800>" has no member "SubtractLeft"
          detected during:
            instantiation of "void flashinfer::sampling::DeviceSamplingFromProb(uint32_t, uint32_t, T, T, flashinfer::vec_t<T, VEC_SIZE>, T &, flashinfer::sampling::SamplingTempStorage<T, BLOCK_THREADS, SCAN_ALGORITHM, REDUCE_ALGORITHM> *) [with VEC_SIZE=4U, BLOCK_THREADS=1024U, SCAN_ALGORITHM=cub::BLOCK_SCAN_WARP_SCANS, REDUCE_ALGORITHM=cub::BLOCK_REDUCE_WARP_REDUCTIONS, T=float]" 
(148): here
            instantiation of "void flashinfer::sampling::SamplingFromProbKernel<BLOCK_THREADS,SCAN_ALGORITHM,REDUCE_ALGORITHM,VEC_SIZE,DType,IdType>(DType *, DType *, IdType *, IdType *, uint32_t) [with BLOCK_THREADS=1024U, SCAN_ALGORITHM=cub::BLOCK_SCAN_WARP_SCANS, REDUCE_ALGORITHM=cub::BLOCK_REDUCE_WARP_REDUCTIONS, VEC_SIZE=4U, DType=float, IdType=int]" 
(343): here
            instantiation of "cudaError_t flashinfer::sampling::SamplingFromProb(T *, T *, IdType *, uint32_t, uint32_t, cudaStream_t) [with T=float, IdType=int]" 
/root/autodl-tmp/wsl/flashinfer/python/csrc/sampling.cu(37): here

/root/autodl-tmp/wsl/flashinfer/python/include/flashinfer/sampling.cuh(109): warning #174-D: expression has no effect
          detected during:
            instantiation of "void flashinfer::sampling::DeviceSamplingFromProb(uint32_t, uint32_t, T, T, flashinfer::vec_t<T, VEC_SIZE>, T &, flashinfer::sampling::SamplingTempStorage<T, BLOCK_THREADS, SCAN_ALGORITHM, REDUCE_ALGORITHM> *) [with VEC_SIZE=4U, BLOCK_THREADS=1024U, SCAN_ALGORITHM=cub::BLOCK_SCAN_WARP_SCANS, REDUCE_ALGORITHM=cub::BLOCK_REDUCE_WARP_REDUCTIONS, T=float]" 
(148): here
            instantiation of "void flashinfer::sampling::SamplingFromProbKernel<BLOCK_THREADS,SCAN_ALGORITHM,REDUCE_ALGORITHM,VEC_SIZE,DType,IdType>(DType *, DType *, IdType *, IdType *, uint32_t) [with BLOCK_THREADS=1024U, SCAN_ALGORITHM=cub::BLOCK_SCAN_WARP_SCANS, REDUCE_ALGORITHM=cub::BLOCK_REDUCE_WARP_REDUCTIONS, VEC_SIZE=4U, DType=float, IdType=int]" 
(343): here
            instantiation of "cudaError_t flashinfer::sampling::SamplingFromProb(T *, T *, IdType *, uint32_t, uint32_t, cudaStream_t) [with T=float, IdType=int]" 
/root/autodl-tmp/wsl/flashinfer/python/csrc/sampling.cu(37): here

/root/autodl-tmp/wsl/flashinfer/python/include/flashinfer/sampling.cuh(109): warning #174-D: expression has no effect
          detected during:
            instantiation of "void flashinfer::sampling::DeviceSamplingFromProb(uint32_t, uint32_t, T, T, flashinfer::vec_t<T, VEC_SIZE>, T &, flashinfer::sampling::SamplingTempStorage<T, BLOCK_THREADS, SCAN_ALGORITHM, REDUCE_ALGORITHM> *) [with VEC_SIZE=4U, BLOCK_THREADS=1024U, SCAN_ALGORITHM=cub::BLOCK_SCAN_WARP_SCANS, REDUCE_ALGORITHM=cub::BLOCK_REDUCE_WARP_REDUCTIONS, T=float]" 
(148): here
            instantiation of "void flashinfer::sampling::SamplingFromProbKernel<BLOCK_THREADS,SCAN_ALGORITHM,REDUCE_ALGORITHM,VEC_SIZE,DType,IdType>(DType *, DType *, IdType *, IdType *, uint32_t) [with BLOCK_THREADS=1024U, SCAN_ALGORITHM=cub::BLOCK_SCAN_WARP_SCANS, REDUCE_ALGORITHM=cub::BLOCK_REDUCE_WARP_REDUCTIONS, VEC_SIZE=4U, DType=float, IdType=int]" 
(343): here
            instantiation of "cudaError_t flashinfer::sampling::SamplingFromProb(T *, T *, IdType *, uint32_t, uint32_t, cudaStream_t) [with T=float, IdType=int]" 
/root/autodl-tmp/wsl/flashinfer/python/csrc/sampling.cu(37): here

/root/autodl-tmp/wsl/flashinfer/python/include/flashinfer/sampling.cuh(109): error: class "cub::BlockAdjacentDifference<__nv_bool, 1024, 1, 1, 800>" has no member "SubtractLeft"
          detected during:
            instantiation of "void flashinfer::sampling::DeviceSamplingFromProb(uint32_t, uint32_t, T, T, flashinfer::vec_t<T, VEC_SIZE>, T &, flashinfer::sampling::SamplingTempStorage<T, BLOCK_THREADS, SCAN_ALGORITHM, REDUCE_ALGORITHM> *) [with VEC_SIZE=2U, BLOCK_THREADS=1024U, SCAN_ALGORITHM=cub::BLOCK_SCAN_WARP_SCANS, REDUCE_ALGORITHM=cub::BLOCK_REDUCE_WARP_REDUCTIONS, T=float]" 
(148): here
            instantiation of "void flashinfer::sampling::SamplingFromProbKernel<BLOCK_THREADS,SCAN_ALGORITHM,REDUCE_ALGORITHM,VEC_SIZE,DType,IdType>(DType *, DType *, IdType *, IdType *, uint32_t) [with BLOCK_THREADS=1024U, SCAN_ALGORITHM=cub::BLOCK_SCAN_WARP_SCANS, REDUCE_ALGORITHM=cub::BLOCK_REDUCE_WARP_REDUCTIONS, VEC_SIZE=2U, DType=float, IdType=int]" 
(343): here
            instantiation of "cudaError_t flashinfer::sampling::SamplingFromProb(T *, T *, IdType *, uint32_t, uint32_t, cudaStream_t) [with T=float, IdType=int]" 
/root/autodl-tmp/wsl/flashinfer/python/csrc/sampling.cu(37): here

/root/autodl-tmp/wsl/flashinfer/python/include/flashinfer/sampling.cuh(109): warning #174-D: expression has no effect
          detected during:
            instantiation of "void flashinfer::sampling::DeviceSamplingFromProb(uint32_t, uint32_t, T, T, flashinfer::vec_t<T, VEC_SIZE>, T &, flashinfer::sampling::SamplingTempStorage<T, BLOCK_THREADS, SCAN_ALGORITHM, REDUCE_ALGORITHM> *) [with VEC_SIZE=2U, BLOCK_THREADS=1024U, SCAN_ALGORITHM=cub::BLOCK_SCAN_WARP_SCANS, REDUCE_ALGORITHM=cub::BLOCK_REDUCE_WARP_REDUCTIONS, T=float]" 
(148): here
            instantiation of "void flashinfer::sampling::SamplingFromProbKernel<BLOCK_THREADS,SCAN_ALGORITHM,REDUCE_ALGORITHM,VEC_SIZE,DType,IdType>(DType *, DType *, IdType *, IdType *, uint32_t) [with BLOCK_THREADS=1024U, SCAN_ALGORITHM=cub::BLOCK_SCAN_WARP_SCANS, REDUCE_ALGORITHM=cub::BLOCK_REDUCE_WARP_REDUCTIONS, VEC_SIZE=2U, DType=float, IdType=int]" 
(343): here
            instantiation of "cudaError_t flashinfer::sampling::SamplingFromProb(T *, T *, IdType *, uint32_t, uint32_t, cudaStream_t) [with T=float, IdType=int]" 
/root/autodl-tmp/wsl/flashinfer/python/csrc/sampling.cu(37): here

/root/autodl-tmp/wsl/flashinfer/python/include/flashinfer/sampling.cuh(109): warning #174-D: expression has no effect
          detected during:
            instantiation of "void flashinfer::sampling::DeviceSamplingFromProb(uint32_t, uint32_t, T, T, flashinfer::vec_t<T, VEC_SIZE>, T &, flashinfer::sampling::SamplingTempStorage<T, BLOCK_THREADS, SCAN_ALGORITHM, REDUCE_ALGORITHM> *) [with VEC_SIZE=2U, BLOCK_THREADS=1024U, SCAN_ALGORITHM=cub::BLOCK_SCAN_WARP_SCANS, REDUCE_ALGORITHM=cub::BLOCK_REDUCE_WARP_REDUCTIONS, T=float]" 
(148): here
            instantiation of "void flashinfer::sampling::SamplingFromProbKernel<BLOCK_THREADS,SCAN_ALGORITHM,REDUCE_ALGORITHM,VEC_SIZE,DType,IdType>(DType *, DType *, IdType *, IdType *, uint32_t) [with BLOCK_THREADS=1024U, SCAN_ALGORITHM=cub::BLOCK_SCAN_WARP_SCANS, REDUCE_ALGORITHM=cub::BLOCK_REDUCE_WARP_REDUCTIONS, VEC_SIZE=2U, DType=float, IdType=int]" 
(343): here
            instantiation of "cudaError_t flashinfer::sampling::SamplingFromProb(T *, T *, IdType *, uint32_t, uint32_t, cudaStream_t) [with T=float, IdType=int]" 
/root/autodl-tmp/wsl/flashinfer/python/csrc/sampling.cu(37): here

/root/autodl-tmp/wsl/flashinfer/python/include/flashinfer/sampling.cuh(109): error: class "cub::BlockAdjacentDifference<__nv_bool, 1024, 1, 1, 800>" has no member "SubtractLeft"
          detected during:
            instantiation of "void flashinfer::sampling::DeviceSamplingFromProb(uint32_t, uint32_t, T, T, flashinfer::vec_t<T, VEC_SIZE>, T &, flashinfer::sampling::SamplingTempStorage<T, BLOCK_THREADS, SCAN_ALGORITHM, REDUCE_ALGORITHM> *) [with VEC_SIZE=1U, BLOCK_THREADS=1024U, SCAN_ALGORITHM=cub::BLOCK_SCAN_WARP_SCANS, REDUCE_ALGORITHM=cub::BLOCK_REDUCE_WARP_REDUCTIONS, T=float]" 
(148): here
            instantiation of "void flashinfer::sampling::SamplingFromProbKernel<BLOCK_THREADS,SCAN_ALGORITHM,REDUCE_ALGORITHM,VEC_SIZE,DType,IdType>(DType *, DType *, IdType *, IdType *, uint32_t) [with BLOCK_THREADS=1024U, SCAN_ALGORITHM=cub::BLOCK_SCAN_WARP_SCANS, REDUCE_ALGORITHM=cub::BLOCK_REDUCE_WARP_REDUCTIONS, VEC_SIZE=1U, DType=float, IdType=int]" 
(343): here
            instantiation of "cudaError_t flashinfer::sampling::SamplingFromProb(T *, T *, IdType *, uint32_t, uint32_t, cudaStream_t) [with T=float, IdType=int]" 
/root/autodl-tmp/wsl/flashinfer/python/csrc/sampling.cu(37): here

/root/autodl-tmp/wsl/flashinfer/python/include/flashinfer/sampling.cuh(109): warning #174-D: expression has no effect
          detected during:
            instantiation of "void flashinfer::sampling::DeviceSamplingFromProb(uint32_t, uint32_t, T, T, flashinfer::vec_t<T, VEC_SIZE>, T &, flashinfer::sampling::SamplingTempStorage<T, BLOCK_THREADS, SCAN_ALGORITHM, REDUCE_ALGORITHM> *) [with VEC_SIZE=1U, BLOCK_THREADS=1024U, SCAN_ALGORITHM=cub::BLOCK_SCAN_WARP_SCANS, REDUCE_ALGORITHM=cub::BLOCK_REDUCE_WARP_REDUCTIONS, T=float]" 
(148): here
            instantiation of "void flashinfer::sampling::SamplingFromProbKernel<BLOCK_THREADS,SCAN_ALGORITHM,REDUCE_ALGORITHM,VEC_SIZE,DType,IdType>(DType *, DType *, IdType *, IdType *, uint32_t) [with BLOCK_THREADS=1024U, SCAN_ALGORITHM=cub::BLOCK_SCAN_WARP_SCANS, REDUCE_ALGORITHM=cub::BLOCK_REDUCE_WARP_REDUCTIONS, VEC_SIZE=1U, DType=float, IdType=int]" 
(343): here
            instantiation of "cudaError_t flashinfer::sampling::SamplingFromProb(T *, T *, IdType *, uint32_t, uint32_t, cudaStream_t) [with T=float, IdType=int]" 
/root/autodl-tmp/wsl/flashinfer/python/csrc/sampling.cu(37): here

/root/autodl-tmp/wsl/flashinfer/python/include/flashinfer/sampling.cuh(109): warning #174-D: expression has no effect
          detected during:
            instantiation of "void flashinfer::sampling::DeviceSamplingFromProb(uint32_t, uint32_t, T, T, flashinfer::vec_t<T, VEC_SIZE>, T &, flashinfer::sampling::SamplingTempStorage<T, BLOCK_THREADS, SCAN_ALGORITHM, REDUCE_ALGORITHM> *) [with VEC_SIZE=1U, BLOCK_THREADS=1024U, SCAN_ALGORITHM=cub::BLOCK_SCAN_WARP_SCANS, REDUCE_ALGORITHM=cub::BLOCK_REDUCE_WARP_REDUCTIONS, T=float]" 
(148): here
            instantiation of "void flashinfer::sampling::SamplingFromProbKernel<BLOCK_THREADS,SCAN_ALGORITHM,REDUCE_ALGORITHM,VEC_SIZE,DType,IdType>(DType *, DType *, IdType *, IdType *, uint32_t) [with BLOCK_THREADS=1024U, SCAN_ALGORITHM=cub::BLOCK_SCAN_WARP_SCANS, REDUCE_ALGORITHM=cub::BLOCK_REDUCE_WARP_REDUCTIONS, VEC_SIZE=1U, DType=float, IdType=int]" 
(343): here
            instantiation of "cudaError_t flashinfer::sampling::SamplingFromProb(T *, T *, IdType *, uint32_t, uint32_t, cudaStream_t) [with T=float, IdType=int]" 
/root/autodl-tmp/wsl/flashinfer/python/csrc/sampling.cu(37): here

5 errors detected in the compilation of "/root/autodl-tmp/wsl/flashinfer/python/csrc/sampling.cu".

**Comment by yzh119** [comment]
@WanBenLe Hi, I checked the cub header files in a cuda 11.8 docker container, it seems cuda 11.8's cub version is too old and `SubtractLeft` was introduced in later versions.

You can compile flashinfer in later cuda versions. I'll fix the cuda 11.8 compilation issues by using old cub::BlockAdjacentDifferent APis, but it will take some time.

**Comment by yzh119** [comment]
Should have been fixed in #265 .

**Comment by WanBenLe** [comment]
> Should have been fixed in #265 .

thanks for your help!
