### ISSUE TITLE
Lacks prebuild whl for PyTorch2.3+cu118

### ISSUE THREAD

**Issue by heheda12345** [flashinfer-ai/flashinfer#314]
This link from Installation Guide is 404: https://flashinfer.ai/whl/cu118/torch2.3/ . Can you help to upload the prebuild whl?

**Comment by yzh119** [comment]
Thanks for reporting, I'll fix it for v0.0.5

**Comment by yzh119** [comment]
Website was fixed.
v0.0.5 release is building: https://github.com/flashinfer-ai/flashinfer/actions/runs/9594555333, hopefully you will see it soon.
