### ISSUE TITLE
How large the page_size could be?

### ISSUE THREAD

**Issue by llx-08** [flashinfer-ai/flashinfer#320]
Hello, I encountered this error:
```
RuntimeError: BatchPrefillWithPagedKVCachePyTorchWrapper::Forward(at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, 
at::Tensor, bool, unsigned int, bool, float, float, float, bool)::<lambda()>::<lambda()>::<lambda()>::<lambda()>::<lambda()>::
<lambda()>::<lambda()>::<lambda()>::<lambda()>::<lambda()>::<lambda()>::<lambda()>::<lambda()>::<lambda()>::<lambda()> 
failed to dispatch page size 512
```
when running `BatchPrefillWithPagedKVCacheWrapper.begin_forward` on A100 after setting the page_size to 512. I am curious about the maximum allowable page_size and the factors that influence this limitation. Any information would be greatly appreciated. Thank you!

**Comment by yzh119** [comment]
Hi, @llx-08 , the restriction of page size was removed in [v0.0.5](https://github.com/flashinfer-ai/flashinfer/releases/tag/v0.0.5). The wheels should be available in a few hours (https://github.com/flashinfer-ai/flashinfer/actions/runs/9594555333).

**Comment by llx-08** [comment]
Oh, thank you!
By the way, I ran some tests with `last_page_len > page_size`, it didn't raise any errors. I'm unsure if this is potentially a hidden bug...

**Comment by llx-08** [comment]
> Hi, @llx-08 , the restriction of page size was removed in [v0.0.5](https://github.com/flashinfer-ai/flashinfer/releases/tag/v0.0.5). The wheels should be available in a few hours (https://github.com/flashinfer-ai/flashinfer/actions/runs/9594555333).

Oh, thank you!
By the way, I ran some tests with `last_page_len > page_size`, it didn't raise any errors. I'm unsure if this is potentially a hidden bug...

**Comment by yzh119** [comment]
We didn't check the len of `last_page_len` in the kernel implementation, it's a undefined behavior.

**Comment by yzh119** [comment]
v0.0.5 was release, I'll close this PR for now.
