### ISSUE TITLE
Build on L20 failed: RuntimeError: FlashInfer requires sm75+

### ISSUE THREAD

**Issue by xTayEx** [flashinfer-ai/flashinfer#371]
Hi! Thank you for the amazing work! I am building `flashinfer` from source on L20. However, when I run `pip install -e .` according to the instructions, the following error occurs:
```bash
Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/xxx/flashinfer/python/setup.py", line 42, in <module>
          raise RuntimeError("FlashInfer requires sm75+")
      RuntimeError: FlashInfer requires sm75+
```

I am using the  `nvcr.io/nvidia/pytorch:24.04-py3` docker image, with `torch==2.3.0a0+6ddf5cf85e.nv24.4` and cuda 12.4 in it. Could you please give me some instructions on how to fix it?

**Comment by yzh119** [comment]
L20 has Ada achitecture (sm89) which is greater than sm75, and it should be supported.

What's our output of `python -c "import torch.utils.cpp_extension as torch_cpp_ext; print(torch_cpp_ext._get_cuda_arch_flags())"`?

**Comment by yzh119** [comment]
One possible reason is that your `TORCH_CUDA_ARCH_LIST` environment variable was set to some earlier architectures. If so, you can either unset it, or manually set it to 89:
```
export TORCH_CUDA_ARCH_LIST="8.9+PTX"
```

**Comment by xTayEx** [comment]
> One possible reason is that your `TORCH_CUDA_ARCH_LIST` environment variable was set to some earlier architectures. If so, you can either unset it, or manually set it to 89:
> 
> ```
> export TORCH_CUDA_ARCH_LIST="8.9+PTX"
> ```

Thank you for your reply! Output of `print(torch_cpp_ext._get_cuda_arch_flags())` is 
```bash
['-gencode=arch=compute_52,code=sm_52', '-gencode=arch=compute_60,code=sm_60', '-gencode=arch=compute_61,code=sm_61', '-gencode=arch=compute_70,code=sm_70', '-gencode=arch=compute_72,code=sm_72', '-gencode=arch=compute_75,code=sm_75', '-gencode=arch=compute_80,code=sm_80', '-gencode=arch=compute_86,code=sm_86', '-gencode=arch=compute_87,code=sm_87', '-gencode=arch=compute_90,code=compute_90', '-gencode=arch=compute_90,code=sm_90']
```

Manually set `TORCH_CUDA_ARCH_LIST` works, I have built `flashinfer` successfully!
