### ISSUE TITLE
Sliding Window Support?

### ISSUE THREAD

**Issue by noamgat** [flashinfer-ai/flashinfer#390]
Hi!
I'm using FlashInfer under vLLM as it is the only implementation there that supports logit capping, which is required for the gemma2 model. However, vLLM disables sliding window attention because FlashInfer doesn't support it, limiting the context length of gemma2 from 8k to 4k.
Is there a plan to add support for this?

**Comment by yzh119** [comment]
Yes, I'm working on that, will be available in v0.1.2

**Comment by noamgat** [comment]
Awesome! Happy to hear!

**Comment by yzh119** [comment]
Done in #406 , available in [v0.1.2 release](https://github.com/flashinfer-ai/flashinfer/releases/tag/v0.1.2).
