### ISSUE TITLE
does flashinfer support AMD GPU?

### ISSUE THREAD

**Issue by zhangnju** [flashinfer-ai/flashinfer#400]
HI, 
I found AMD CK library had been included in the 3rdparty folder. does it mean flashinfer support AMD GPU?
if support, could you help share more info about how to build and install flashinfer on AMD GPU?

Thanks

**Comment by yzh119** [comment]
Hi @zhangnju , some of the community members are working on AMD GPU related support, the efforts include:
1. implementing the triton version of attention operators (lead by @LeshengJin ), which should be compatible with AMD GPUs.
2. porting misc kernels such as sampling to RoCM (lead by @danielpyon), which will upstreamed to these repo.
3. integrating composable kernel implementations such as group gemm.

We also welcome contributions from the community.

**Comment by zhangnju** [comment]
Thanks for your info @yzh119

**Comment by liunn5** [comment]
@yz119 你好，咨询下。如果我有个新的第三方的GPU。 怎么做能够让flashinfer支持这个GPU呢
