### ISSUE TITLE
Please support a wheel with cuda 12.5! Thanks

### ISSUE THREAD

**Issue by BlackBearBiscuit** [flashinfer-ai/flashinfer#464]
Please support a wheel with cuda 12.5! Thanks

**Comment by yzh119** [comment]
FlashInfer's cuda version follows your pytorch's cuda version, and this has nothing to do with your nvcc or cuda driver version in your operating system, pytorch do not have an official cuda 12.5 release.

You can check your pytorch cuda version by `python -c "import torch; print(torch.version.cuda)"` (it should be 11.8, 12.1 or 12.4), and install flashinfer that matches with this version, no matter what your operating system's cuda version is (if your os has cuda version of 12.5 and your pytorch has cuda version of 12.4, just install flashinfer with cuda 12.4 and it should work fine).

**Comment by BlackBearBiscuit** [comment]
Thank you !
