### ISSUE TITLE
[mixtral 8*7B A800*2] some times the infer gets stuck in the kernel call of flashinfer

### ISSUE THREAD

**Issue by CSEEduanyu** [flashinfer-ai/flashinfer#488]
When this happens, GPU usage will approach 100% and flashinfer's kernel call will not return,It is normal on single card llama2-13B.

**Comment by CSEEduanyu** [comment]
I think this is a hardware-related problem, because after I changed a batch of machines, it is normal. I want to know how to locate and solve this problem?

**Comment by CSEEduanyu** [comment]
Does anyone else have similar questions? Thanks for your reply

**Comment by yzh119** [comment]
Can you provide more information? e.g. what are the input arguments you provided in `plan` function, what are the input shapes you provided in the `run` function, did you use enable CUDAGraph, etc.

**Comment by CSEEduanyu** [comment]
> Can you provide more information? e.g. what are the input arguments you provided in `plan` function, what are the input shapes you provided in the `run` function, did you use enable CUDAGraph, etc.
I'm using sglang v0.2.14 (the latest version of flashinfer) with default startup parameters and "disable_cuda_graph": true. When I kept making requests at 15qps (input_length<100), after about 5 minutes the whole service would get stuck in the attention kernel. When I additionally set "disable_flashinfer": true, the exception goes away.

**Comment by CSEEduanyu** [comment]
> Can you provide more information? e.g. what are the input arguments you provided in `plan` function, what are the input shapes you provided in the `run` function, did you use enable CUDAGraph, etc.

I'm using sglang v0.2.14 (flashinfer-0.1.6+cu124torch2.4-cp310-cp310-linux_x86_64) with default startup parameters and "disable_cuda_graph": true. When I kept making requests at 15qps (input_length<100), after about 5 minutes the whole service would get stuck in the attention kernel. When I additionally set "disable_flashinfer": true, the exception goes away.

**Comment by CSEEduanyu** [comment]
This exception is only present in mixtral8*7B and only on some machines, but it seems to me that the environment (dockerfile and cuda driver) is the same on these machines (A800 80GB). @yzh119

**Comment by CSEEduanyu** [comment]
Supplementary information: I found that the reason for the exception is the all reduce NCCL timeout, maybe there is an exception in the NCCL between some machines. But it is strange that this bug is triggered only when flashinfer is turned on, maybe flashinfer has more transferred content?

**Comment by yzh119** [comment]
> But it is strange that this bug is triggered only when flashinfer is turned on, 

It's hard to say.. Have you tried `CUDA_LAUNCH_BLOCKING=1`?

**Comment by CSEEduanyu** [comment]
> > But it is strange that this bug is triggered only when flashinfer is turned on,
> 
> It's hard to say.. Have you tried `CUDA_LAUNCH_BLOCKING=1`?

Sorry for the error in the previous test. It has been confirmed that the problem has nothing to do with flashinfer. I will close this issue.
