### ISSUE TITLE
Error while trying to install flashinfer

### ISSUE THREAD

**Issue by Islam231bi** [flashinfer-ai/flashinfer#496]
```bash
pip install flashinfer==0.0.8 -i https://flashinfer.ai/whl/cu121/torch2.3/
```
I get the following after downloading 50% of the file:
```bash
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    flashinfer==0.0.8 from https://github.com/flashinfer-ai/flashinfer/releases/download/v0.0.8/flashinfer-0.0.8%2Bcu121torch2.3-cp310-cp310-linux_x86_64.whl#sha256=ef51aa573a729cbf09eaab103495845fefbdc0ac8cf89ae45013d8e406f011fa:
        Expected sha256 ef51aa573a729cbf09eaab103495845fefbdc0ac8cf89ae45013d8e406f011fa
             Got        1f245af7ef99172932c992c469272820f0cc0717b3a9499d93ac814a0a2d3254
```
I tried going to releases and wget the exact file, it downloads about 80% of the file and then throws auth error

**Comment by zhyncs** [comment]
This usually just requires a simple retry, or you can directly specify the whl link of the GitHub release.

**Comment by bassuniz** [comment]
> This usually just requires a simple retry, or you can directly specify the whl link of the GitHub release.

I actually tried all these options but still same error. I tried wget from the releases in github, tried normal download, and using pip. I also tried different versions.
