### ISSUE TITLE
Add an `out` argument to `rmsnorm`, `gemma_rmsnorm`

### ISSUE THREAD

**Issue by merrymercy** [flashinfer-ai/flashinfer#500]
Currently, the rmsnorm function does not allow the passing of an output buffer. It should support an `out` argument, similar to other activation functions.

https://github.com/flashinfer-ai/flashinfer/blob/8f186cf0ea07717727079d0c92bbe9be3814a9cb/python/flashinfer/norm.py#L33-L35

https://github.com/flashinfer-ai/flashinfer/blob/8f186cf0ea07717727079d0c92bbe9be3814a9cb/python/flashinfer/activation.py#L45

When define the order of arguments, it is better to align it with vllm's custom op so we can change them easily.
https://github.com/vllm-project/vllm/blob/fc990f97958636ce25e4471acfd5651b096b0311/vllm/model_executor/layers/layernorm.py#L62

**Comment by merrymercy** [comment]
cc @zhyncs

**Comment by zhyncs** [comment]
Ok

**Comment by yzh119** [comment]
sounds good
