### ISSUE TITLE
Does FlashInfer support variable-length inputs?

### ISSUE THREAD

**Issue by Liu-xiandong** [flashinfer-ai/flashinfer#501]
Does FlashInfer currently have a result for variable-length inputs, similar to the `varlen_fwd` interface in Flash Attention, which supports different sequence lengths for each batch?

**Comment by yzh119** [comment]
Hi, of course, variable length are described as RaggedTensor data structures:

https://docs.flashinfer.ai/tutorials/kv_layout.html#ragged-tensor

and the corresponding API:

https://docs.flashinfer.ai/api/python/prefill.html#flashinfer.prefill.BatchPrefillWithRaggedKVCacheWrapper
