### ISSUE TITLE
Have any plans to optimize the prefill kernel for the Hopper architecture?

### ISSUE THREAD

**Issue by alexngng** [flashinfer-ai/flashinfer#521]
I notice that the Flashinfer prefill kernel is much slower than FA3 and TRT-LLM FMHA on SM90.
Do you have any plans to use some SM90 features for optimization?

Here is some data I tested on an SM90. Single H20 GPU, Llama2 7B.

| Tokens Number | TRT-LLM FMHA  | FA3          | Flashinfer   |
|---------------|--------------|--------------|--------------|
| 512 x 1       | 37638.6      | 39,334.6     | 74966.6      |
| 512 x 2       | 54729.9      | 61,680.4     | 114800.0     |
| 512 x 4       | 103388.8     | 113,056.2    | 190688.4     |

**Comment by yzh119** [comment]
Hi @alexngng , yes for sure. I still have some slight bug to fix and it's coming soon :)

**Comment by jason-huang03** [comment]
Really looking forward to it!

**Comment by jpf888** [comment]
@yzh119  
Hello I am using flashinfer single_prefill, I want to know if there are plans to support batch_prefill, now I only see attention_kernel_prefill_with_paged_kv_cache, but this interface couples kv cache

**Comment by taegeonum** [comment]
@yzh119 Hello, any update?

**Comment by yzh119** [comment]
@alexngng @taegeonum @jason-huang03 
Done in #667 .

**Comment by taegeonum** [comment]
@yzh119 Do you have a plan for supporting FP8 Q,K,V?
