### ISSUE TITLE
WHL file download failure

### ISSUE THREAD

**Issue by Rssevenyu** [flashinfer-ai/flashinfer#524]
Download address:
https://flashinfer.ai/whl/cu121/torch2.4/flashinfer/

Failed several times, please check if there is a problem

**Comment by yzh119** [comment]
The wheels are hosted on GitHub and it might be your network connection issue. I can't reproduce the issue on several desktop and servers.

You can try using the JIT mode by install flashinfer from source (the JIT mode defers cuda kernel compilation and the installation process should be fast).

From next version on we will upload wheel of flashinfer JIT (it do not include kernel binary thus the wheel size should be small) to pypi, which is more accessible than wheels hosted on GitHub.

**Comment by Rssevenyu** [comment]
Thank you for your reply, I will try again. Meanwhile,
I am using VLLM and need to use Flashfer, but at the same time, the logs in VLLM did not remind me that the error was caused by not installing Flashinfer. It took me a long time to understand this. I hope you can work together to solve this problem. If it is due to an uninstalled issue, please remind the user that Flashinfer is not installed.
