### ISSUE TITLE
[Bug] data_type default overwrites q_data_type

### ISSUE THREAD

**Issue by cyang49** [flashinfer-ai/flashinfer#543]
https://github.com/flashinfer-ai/flashinfer/blob/78e26e47b95bea994ad2a47e1b1f42810363429c/python/flashinfer/decode.py#L587

Current logic sets default to `data_type` and the comment suggests that users should set `q_data_type` and `kv_data_type` instead.

However, if a user doesn't explicitly set `data_type=None`, it causes the explicitly set `q_data_type` and `kv_data_type` to be overwritten by default `data_type=float16`. I don't think this is the intended behavior and it's causing confusion.

**Comment by yzh119** [comment]
@cyang49 thank you for spotting this bug!

**Comment by cyang49** [comment]
Thanks for the fix!
