### ISSUE TITLE
[Question] smem_size Computation of Prefill Kernels

### ISSUE THREAD

**Issue by cyang49** [flashinfer-ai/flashinfer#550]
I saw that in several places in the prefill code, smem_size is computed using `DTypeQ` for the kv storage too. Is this a bug that allocates more than needed for when DTypeKV is lower precision?

https://github.com/flashinfer-ai/flashinfer/blob/47583b3b32b366d5872c54b3b861b41a8afc57df/include/flashinfer/attention/prefill.cuh#L2258-L2261

https://github.com/flashinfer-ai/flashinfer/blob/47583b3b32b366d5872c54b3b861b41a8afc57df/include/flashinfer/attention/prefill.cuh#L2156-L2159

**Comment by yzh119** [comment]
It's just my laziness because in current implementation `sizeof(DTypeQ) >= sizeof(DTypeKV)` always holds so for fp8 case, the smem computation is always larger than actual size.

The idea way is to use `union` to compute smem usage.
