### ISSUE TITLE
Release binary for torch 2.5

### ISSUE THREAD

**Issue by merrymercy** [flashinfer-ai/flashinfer#575]
pytorch 2.5 has been released.

**Comment by yzh119** [comment]
I think torch 2.4 wheels should work for torch 2.5 because there are no ABI changes.

**Comment by zhyncs** [comment]
ref https://github.com/sgl-project/sglang/pull/1849#issuecomment-2478366910

**Comment by zhyncs** [comment]
ref https://github.com/sgl-project/sglang/pull/2069
