### ISSUE TITLE
[Usage] How to quickly compile a cu/cuh file and complete testing

### ISSUE THREAD

**Issue by Abatom** [flashinfer-ai/flashinfer#577]
I want to modify a function in the norm.cuh file,and I only want to compile this one file or the fewest possible files without using the`pip install -e .`command to compile all files,as I did today,which took at least 8 hours to execute.This is too inefficient for debugging.Moreover,after the compilation is completed,`import flashinfer` results in an error.I am using version 0.1.6.Additionally,the main branch currently has compilation errors.

I want to modify the norm.cuh file,then quickly compile it,and finally test it using `pytest test_norm.py`.

**Comment by yzh119** [comment]
Our latest codebase in main branch support JIT which don't compile kernels ahead of time
> Moreover,after the compilation is completed,import flashinfer results in an error.

Can you show me the error message?

**Comment by Abatom** [comment]
> Our latest codebase in main branch support JIT which don't compile kernels ahead of time

@yzh119 This means that after I modify norm.cuh, I can directly use pytest norm.py to test and verify, right?

```bash
# pytest test_norm.py
ImportError while loading conftest '/home/Abatom/flashinfer/tests/conftest.py'.
conftest.py:4: in <module>
    import flashinfer
E   ModuleNotFoundError: No module named 'flashinfer'
```

**Comment by Abatom** [comment]
@yzh119 In other words, can you teach me how to quickly use pytest norm.py to verify after modifying norm.cuh? Or instead of using pytest norm.py, is there a better way to quickly verify my modifications to norm.cuh?

**Comment by yzh119** [comment]
> This means that after I modify norm.cuh, I can directly use pytest norm.py to test and verify, right?

Yes, if you install flashinfer in JIT mode.

`pip install -e .` do not trigger compilation in JIT mode, if defers compilation to the first time you run the kernel.
