### ISSUE TITLE
I cannot find FlexAttention-like api.

### ISSUE THREAD

**Issue by BirdChristopher** [flashinfer-ai/flashinfer#612]
Hi, I'm pretty interested in the flexattention-like api mentioned in October lmsys meetup. But I can't find any introduction related. Is there anything I miss in documentation?

**Comment by yzh119** [comment]
You can try https://github.com/flashinfer-ai/flashinfer/blob/main/tests/test_jit_example.py at this moment.

The APIs are subject to changes because this feature is still experimental.

**Comment by BirdChristopher** [comment]
Got it. Really looking forward to next release!
