### ISSUE TITLE
[Question] Why is it necessary to use block.sync at this position?

### ISSUE THREAD

**Issue by luliyucoordinate** [flashinfer-ai/flashinfer#614]
https://github.com/flashinfer-ai/flashinfer/blob/v0.1.6/include/flashinfer/attention/prefill.cuh#L1253

https://github.com/flashinfer-ai/flashinfer/blob/v0.1.6/include/flashinfer/attention/prefill.cuh#L1265

**Comment by yzh119** [comment]
Compute sanitizer (https://docs.nvidia.com/compute-sanitizer/ComputeSanitizer/index.html#racecheck-tool) reports race error when I removed these synchronizations, actually I didn't observe correctness issue when I removed them.

**Comment by luliyucoordinate** [comment]
thx
