### ISSUE TITLE
The PyTorch API reference for flashinfer.rope.apply_rope_pos_ids appears to contain inaccuracies.

### ISSUE THREAD

**Issue by ovowei** [flashinfer-ai/flashinfer#615]
In the code at [this line](https://github.com/flashinfer-ai/flashinfer/blob/b53a46f8b073e66fbc8fe888e87517b3aea8bd2d/tests/test_rope.py#L216), the pos_ids used have a shape of (nnz). However, the documentation at [flashinfer.rope.apply_rope_pos_ids](https://docs.flashinfer.ai/api/python/_generate/flashinfer.rope.apply_rope_pos_ids.html) describes pos_ids as having a shape of (batch_size + 1).

**Comment by yzh119** [comment]
Thank you for reporting this issue, pos_ids should have shape (nnz,), and the documentation was not updated.
