### ISSUE TITLE
Performance between ragged/paged prefill

### ISSUE THREAD

**Issue by ZhongYingMatrix** [flashinfer-ai/flashinfer#637]
Hi,

Thank you for your excellent work! I am comparing the performance between ragged and paged prefill. To do this, I modified the following file:

Original: [bench_batch_prefill.cu](https://github.com/flashinfer-ai/flashinfer/blob/v0.1.6/src/bench_batch_prefill.cu)
Modified: [bench_batch_prefill_paged.cu](https://gist.github.com/ZhongYingMatrix/4d532c0f197d4e8dd9dbc88235104897)
However, I observed only a small performance difference (mostly 1-2%) between the ragged and paged versions. According to @yzh119's comment in [this issue](https://github.com/sgl-project/sglang/issues/2172#issuecomment-2497043890), the expected performance difference should be around 10% or more.

Am I missing something in my setup or approach? Any guidance would be greatly appreciated. Thank you!

**Comment by ZhongYingMatrix** [comment]
To add, I tested on L40/H20.

**Comment by yzh119** [comment]
> According to @yzh119's comment in https://github.com/sgl-project/sglang/issues/2172#issuecomment-2497043890, the expected performance difference should be around 10% or more.

It depends on sequence length, would you mind trying longer sequence length?

btw 10% is just a reference number (on A100) and should be hardware specific, actually we are working hard to make sparse (paged) version as fast as contiguous (ragged) version :)

**Comment by yzh119** [comment]
btw, I'll really appreciate it you contribute [bench_batch_prefill_paged.cu](https://gist.github.com/ZhongYingMatrix/4d532c0f197d4e8dd9dbc88235104897) to flashinfer :)
