### ISSUE TITLE
PR 636 miss fix for FusedAddRMSNorm function

### ISSUE THREAD

**Issue by Atream** [flashinfer-ai/flashinfer#645]
In https://github.com/flashinfer-ai/flashinfer/pull/636/, you write `const uint32_t smem_size = (ceil_div(num_warps, 4) * 4 + d) * sizeof(float);` in GemmaFusedAddRMSNorm but not in FusedAddRMSNorm function.

**Comment by yzh119** [comment]
Hi @Atream , yes I think you are correct, would you mind creating a pull request to fix it?

**Comment by Atream** [comment]
Yes, I've created a pull request to address the issue. You can find it here https://github.com/flashinfer-ai/flashinfer/pull/646 . Please review and let me know if there's anything else that needs to be adjusted. Thanks for your response!
