### ISSUE TITLE
Runtime error building kernels

### ISSUE THREAD

**Issue by sugunav14** [flashinfer-ai/flashinfer#647]
Hi, I am trying to run batched prefill attention using the latest flashinfer repository and am getting an error in building the kernels. I have attached a log file for reference.
[log.log](https://github.com/user-attachments/files/18012430/log.log)

**Comment by yzh119** [comment]
Seems to be something wrong with our JIT templates, we will fix it.

Would you mind trying compiling in AOT mode? 
https://docs.flashinfer.ai/installation.html#install-from-source

Or using our pre-built wheels https://github.com/flashinfer-ai/flashinfer-nightly/releases

**Comment by yzh119** [comment]
The JIT compilation bug was fixed in #670
