### ISSUE TITLE
Loading jit ops when using aot wheel

### ISSUE THREAD

**Issue by flyingcow8** [flashinfer-ai/flashinfer#653]
![image](https://github.com/user-attachments/assets/7cf594a1-b58d-4eb6-a195-fe41d7210c5f)
I found it going to the exception condition

**Comment by flyingcow8** [comment]
commit id: 8e3d258748da59156e6c862a3583b3c2b84fab9f

**Comment by yzh119** [comment]
Hi @flyingcow8 I can't reproduce the issue, how did you use aot wheel? Is it installed from source (if so, what's the instruction you used to install AOT mode)?

**Comment by flyingcow8** [comment]
> Hi @flyingcow8 I can't reproduce the issue, how did you use aot wheel? Is it installed from source (if so, what's the instruction you used to install AOT mode)?

I built it from source, using this command:
```
TORCH_CUDA_ARCH_LIST="8.0" FLASHINFER_ENABLE_AOT=1 python3 -m build --no-isolation --wheel
```
Then I installed the wheel in the dist directory. My python is 3.8.20 and pytorch is 2.4.1. By the way, there is a list error in cascade.py when using python 3.8 :)

**Comment by flyingcow8** [comment]
Maybe my mistake, it is ok now
