### ISSUE TITLE
[Bug] Wheel naming issue

### ISSUE THREAD

**Issue by zhyncs** [flashinfer-ai/flashinfer#663]
ref
https://github.com/flashinfer-ai/flashinfer/pull/643
https://github.com/flashinfer-ai/flashinfer/pull/659
https://github.com/flashinfer-ai/flashinfer/pull/660
https://github.com/flashinfer-ai/flashinfer/pull/662

@ur4t @xslingcn 

Before

```
flashinfer-0.1.6+cu124torch2.4-cp310-cp310-linux_x86_64.whl
```

After

```
flashinfer-0.1.6-cp38-abi3-linux_x86_64.whl
```

Expected

```
flashinfer-0.1.6+cu124torch2.4-cp38-abi3-linux_x86_64.whl
```

**Comment by zhyncs** [comment]
ref https://github.com/flashinfer-ai/flashinfer/pull/643/files#r1885003167

**Comment by zhyncs** [comment]
CUDA and Torch version info missing: `+cu124torch2.4`

**Comment by zhyncs** [comment]
@ur4t Could you help fix this issue? Thanks.

**Comment by xslingcn** [comment]
setup.py is taking `FLASHINFER_BUILD_VERSION` for top priority.
https://github.com/flashinfer-ai/flashinfer/blob/b1b1fb8fb36a6442067a4d6ceb64319a40d854d4/setup.py#L47-L55
It seems we specify this env variable in the nightly building script, while the cuda/torch version is missing:
https://github.com/flashinfer-ai/flashinfer-nightly/blob/f28fab619a21573c9e1ec0dba8bec841c890cfed/.github/workflows/nightly-release.yml#L51-L52

https://github.com/flashinfer-ai/flashinfer-nightly/blob/f28fab619a21573c9e1ec0dba8bec841c890cfed/.github/workflows/nightly-release.yml#L62

**Comment by zhyncs** [comment]
Yeah I think before these https://github.com/flashinfer-ai/flashinfer/pull/643 https://github.com/flashinfer-ai/flashinfer/pull/659 https://github.com/flashinfer-ai/flashinfer/pull/660 https://github.com/flashinfer-ai/flashinfer/pull/662 the nightly works

**Comment by xslingcn** [comment]
Not sure how this was handled before we changed packaging, but one fix I can think of now is:

```
diff --git a/.github/workflows/nightly-release.yml b/.github/workflows/nightly-release.yml
index 0c919e9..9c6c4ae 100644
--- a/.github/workflows/nightly-release.yml
+++ b/.github/workflows/nightly-release.yml
@@ -48,7 +48,10 @@ jobs:
           sed -i 's/+cu/\.cu/g' scripts/run-ci-build-wheel.sh
           sed -i 's|/ci-cache|/opt/dlami/nvme/flashinfer/github|g' scripts/run-ci-build-wheel.sh
           sed -i '/mkdir -p "\$CONDA_pkgs_dirs" "\$XDG_CACHE_HOME"/d' scripts/run-ci-build-wheel.sh
-          version="$(cat version.txt)"+"$(git rev-parse HEAD | cut -c1-7)"
+          CUDA_VERSION=${{ matrix.cuda }}
+          CUDA_MAJOR="${CUDA_VERSION%.*}"
+          CUDA_MINOR="${CUDA_VERSION#*.}"
+          version="$(cat version.txt)+$(git rev-parse HEAD | cut -c1-7)+cu${CUDA_MAJOR}${CUDA_MINOR}torch${{ matrix.torch }}"
           echo "VERSION=$version" >> $GITHUB_ENV
           echo "version=$version" >> $GITHUB_OUTPUT
         id: get_version
```

**Comment by zhyncs** [comment]
There are several ways to ensure nightly compatibility. I want to know the name given when version 0.2.0 was released for the main branch of FlashInfer (not nightly). Also, it would be better if we could be compatible with both the nightly and stable releases.

**Comment by xslingcn** [comment]
This issue doesn't exist in the stable release workflow, because we don't specify `FLASHINFER_BUILD_VERSION` so it will use the `FLASHINFER_LOCAL_VERSION` as passed in:

https://github.com/flashinfer-ai/flashinfer/blob/b1b1fb8fb36a6442067a4d6ceb64319a40d854d4/scripts/run-ci-build-wheel.sh#L41

**Comment by xslingcn** [comment]
> I want to know the name given when version 0.2.0 was released for the main branch of FlashInfer (not nightly).

It will be something like `flashinfer-0.2.0+cu12.4torch2.4-cp38-abi3-linux_x86_64.whl`.

**Comment by zhyncs** [comment]
I see. I'll help with the nightly build issue.

**Comment by zhyncs** [comment]
fixed with https://github.com/flashinfer-ai/flashinfer-nightly/pull/4
