### ISSUE TITLE
Is it the case that current flashinfer 0.2.0 does not support fp8 with flash attention 3 backend?

### ISSUE THREAD

**Issue by Dr-Left** [flashinfer-ai/flashinfer#693]
I saw at https://github.com/flashinfer-ai/flashinfer/blob/63fa200edbe4a54dcba36943ac0d0987f5292628/flashinfer/utils.py#L302
you noted that fp8 is not supported in FA3 backend. Is it still the case now?

Currently I am facing compiling errors when using fp8 with flash-infer==0.2.0, FA-3 backend. (I manually passed the backend="fa3")

**Comment by yzh119** [comment]
Yes that's true.

We delayed the fp8 for fa3 template because:
1. we need to co-design the kv-cache storage for best-performance with fp8 tensor cores.
2. we plan to integrate tricks in SageAttention2 paper for numerical stability.

The eta is v0.2.2 release (early Jan).

**Comment by Dr-Left** [comment]
A related question:

I ran benchmark on `flashinfer==0.2.0` with FA-2 backend, fp8 and bf16 respectively, but the result shows that **fp8 is significantly slower than bf16** under any circumstances (all batch sizes, all seq lengths, as shown in the table below), is it because FA-2 doesn't support fp8 internally, so the calculations are actually done with the numbers upcasted to bf16?

Env: 
flashinfer==0.2.0
torch==2.3
cuda==12.1

Result: 
# Flashinfer Attention (Prefill)
|   Batch |   Seqlen |   Q Heads |   K Heads |   Flash Attention (us) |   Flashinfer_bf16 (us) |   Flashinfer_fp8 (us) |
|--------:|---------:|----------:|----------:|-----------------------:|-----------------------:|----------------------:|
|       1 |     2048 |         8 |         1 |                     66 |                    105 |                   157 |
|       1 |     4096 |         8 |         1 |                    200 |                    171 |                   333 |
|       1 |     8192 |         8 |         1 |                    583 |                    519 |                  1018 |
|       1 |    16384 |         8 |         1 |                   1838 |                   1744 |                  3425 |
|       1 |    32768 |         8 |         1 |                   6388 |                   6287 |                 12274 |
|       1 |    65536 |         8 |         1 |                  24172 |                  23966 |                 47096 |
|       1 |   131072 |         8 |         1 |                 100479 |                  97227 |                182525 |
|       4 |     2048 |         8 |         1 |                    163 |                    157 |                   300 |
|       4 |     4096 |         8 |         1 |                    489 |                    500 |                   928 |
|       4 |     8192 |         8 |         1 |                   1660 |                   1664 |                  3195 |
|       4 |    16384 |         8 |         1 |                   6105 |                   6107 |                 11957 |
|       4 |    32768 |         8 |         1 |                  23774 |                  23704 |                 46376 |
|       4 |    65536 |         8 |         1 |                  97949 |                  94824 |                181893 |
|       4 |   131072 |         8 |         1 |                 403986 |                 395060 |                719939 |
|       8 |     2048 |         8 |         1 |                    262 |                    270 |                   493 |
|       8 |     4096 |         8 |         1 |                    868 |                    876 |                  1682 |
|       8 |     8192 |         8 |         1 |                   3131 |                   3132 |                  6158 |
|       8 |    16384 |         8 |         1 |                  11962 |                  12015 |                 23633 |
|       8 |    32768 |         8 |         1 |                  47260 |                  47542 |                 91949 |
|       8 |    65536 |         8 |         1 |                 195112 |                 189858 |                362429 |
|       8 |   131072 |         8 |         1 |                 808963 |                 795586 |               1438110 |
|      16 |     2048 |         8 |         1 |                    469 |                    473 |                   898 |
|      16 |     4096 |         8 |         1 |                   1613 |                   1629 |                  3229 |
|      16 |     8192 |         8 |         1 |                   6051 |                   6148 |                 12216 |
|      16 |    16384 |         8 |         1 |                  23715 |                  23887 |                 46826 |
|      16 |    32768 |         8 |         1 |                  96165 |                  94597 |                183254 |
|      16 |    65536 |         8 |         1 |                 390495 |                 382336 |                723410 |
|      32 |     2048 |         8 |         1 |                    876 |                    872 |                  1721 |
|      32 |     4096 |         8 |         1 |                   3110 |                   3145 |                  6330 |
|      32 |     8192 |         8 |         1 |                  12105 |                  12038 |                 24017 |
|      32 |    16384 |         8 |         1 |                  47278 |                  47948 |                 93193 |
|      32 |    32768 |         8 |         1 |                 191468 |                 190324 |                365702 |

Reproduction code: https://gist.github.com/Dr-Left/1077cc358ee3d9309cf95d2a54019107

**Comment by yzh119** [comment]
Yes the current fp8 kernel is far from optimal, it converts key/value from fp8 to bf16 on-the-fly and use bf16 tensor cores. When query length is longer than the tile size (usually 128), such fused kernel is worse than two kernels (1) first convert input from fp8 to bf16 explictly (2) then use bf16 attention kernels. Because we have to dequantize key/values again and again (once per query tile) in the fused kernel. So the fused kernel only make sense when query length is small (e.g. decoding), otherwise two kernels will be better.

If you are using GPUs earlier than H100, things are even worse because there lack hardware primitives for fast f8/f16 conversion.

**Comment by Dr-Left** [comment]
Got it. Thank you for your prompt reply.
